include_directories("${CMAKE_SOURCE_DIR}/3rd_party/glad/include")
include_directories("${CMAKE_SOURCE_DIR}/3rd_party/glfw3/include")
include_directories("${CMAKE_SOURCE_DIR}/3rd_party/glm")
include_directories("${CMAKE_SOURCE_DIR}/3rd_party/freeimage/include")
include_directories("${CMAKE_SOURCE_DIR}/3rd_party/opencv/include")
link_directories("${CMAKE_SOURCE_DIR}/3rd_party/glad/lib/windows")
link_directories("${CMAKE_SOURCE_DIR}/3rd_party/glfw3/lib/windows")

if(${CMAKE_BUILD_TYPE} MATCHES Debug)
    link_directories("${CMAKE_SOURCE_DIR}/3rd_party/freeimage/lib/windows/debug")
    link_directories("${CMAKE_SOURCE_DIR}/3rd_party/opencv/lib/windows/debug")
else()
    link_directories("${CMAKE_SOURCE_DIR}/3rd_party/freeimage/lib/windows/release")
    link_directories("${CMAKE_SOURCE_DIR}/3rd_party/opencv/lib/windows/release")
endif()